server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?&characterEncoding=utf-8&useSSL=false #数据库的连接信息
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    username: root #数据库的用户名
    password: 123456 #数据库的密码
    type: com.alibaba.druid.pool.DruidDataSource #使用druid连接池
  #jpa配置
  jpa:
    database: mysql #数据库类型
    show-sql: true #是否在控制台答应sql
    hibernate:
      ddl-auto: create #可选项:none、create、create-drop、update、validate
#      naming:
        #下面的配置为关闭驼峰转下划线命名规则，不配置该项，默认为开启状态
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #数据库方言
    properties:
     hibernate:
      format_sql: true #是否格式化sql